export const FETCH_RENTALS = 'FETCH_RENTALS';
export const FETCH_RENTAL_BY_ID_SUCCESS = 'FETCH_RENTAL_BY_ID_SUCCESS';
export const FETCH_RENTAL_BY_ID_INIT = 'FETCH_RENTAL_BY_ID_INIT';
export const FETCH_RENTALS_SUCCESS = 'FETCH_RENTALS_SUCCESS';
export const FETCH_RENTALS_BY_RATING = 'FETCH_RENTALS_BY_RATING';

export const FETCH_USER_BOOKINGS_SUCCESS = 'FETCH_USER_BOOKINGS_SUCCESS';
export const FETCH_USER_BOOKINGS_FAIL = 'FETCH_USER_BOOKINGS_FAIL';
export const FETCH_USER_BOOKINGS_INIT = 'FETCH_USER_BOOKINGS_INIT';

export const CREATE_BOOKING_FAIL = ' CREATE_BOOKING_FAIL'
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS'
export const RESET_BOOKING_STATE = 'RESET_BOOKING_STATE';

export const FETCH_RENTALS_INIT = 'FETCH_RENTALS_INIT';
export const FETCH_RENTALS_FAIL = 'FETCH_RENTALS_FAIL';

export const UPDATE_RENTAL_SUCCESS = 'UPDATE_RENTAL_SUCCESS';
export const UPDATE_RENTAL_FAIL = 'UPDATE_RENTAL_FAIL';
export const UPDATE_INFO_SUCCESS = "UPDATE_INFO_SUCCESS";
export const UPDATE_INFO_FAIL = "UPDATE_INFO_FAIL"
export const RESET_RENTAL_ERRORS = 'RESET_RENTAL_ERRORS';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const FETCH_USER_BY_ID_SUCCESS = 'FETCH_USER_BY_ID_SUCCESS';
export const FETCH_USER_BY_ID_INIT = 'FETCH_USER_BY_ID_INIT';

export const SEND_MAIL_SUCCESS = 'SEND_MAIL_SUCCESS';
export const SEND_MAIL_FAILURE = 'SEND_MAIL_FAILURE';

export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS'; 
export const UPLOAD_AVATAR_FAILURE = 'UPLOAD_AVATAR_FAILURE'; 

export const RESET_USER_STATE = 'RESET_USER_STATE';
export const RELOAD_MAP = 'RELOAD_MAP';
export const RELOAD_MAP_FINISH = 'RELOAD_MAP_FINISH';

export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS'
export const DELETE_BOOKING_FAILURE = 'DELETE_BOOKING_FAILURE'

export const DELETE_RENTAL_SUCCESS = 'DELETE_RENTAL_SUCCESS';
export const DELETE_RENTAL_FAILURE = 'DELETE_RENTAL_FAILURE';
export const CREATE_RENTAL_SUCCESS = 'CREATE_RENTAL_SUCCESS';
export const CREATE_RENTAL_FAILURE = "CREATE_RENTAL_FAILURE";
export const RESET_RENTALS_STATE = "RESET_RENTAL_STATE"
export const RESET_RENTAL_STATE = "RESET_RENTAL_STATE"
export const FETCH_BOOKING_BY_ID = "FETCH_BOOKING_BY_ID";
export const FETCH_BOOKING_BY_ID_SUCCESS ="FETCH_BOOKING_BY_ID_SUCCESS";
export const FETCH_BOOKING_BY_ID_FAILURE = "FETCH_BOOKING_BY_ID_FAILURE";
export const SORT_BOOKING = "SORT_BOOKING"
export const SORT_BY_PRICE = "SORT_BY_PRICE"
export const SORT_BY_DAYS = "SORT_BY_DAYS"
export const SORT_BY_DATE = "SORT_BY_DATE"

